name: Deploy Supabase

on:
  push:
    branches: [main]
    paths:
      - 'backend/supabase/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_ID: ${{ vars.SUPABASE_PROJECT_ID }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Install Supabase CLI
        run: npm install -g supabase
      
      - name: Login to Supabase
        run: supabase login --access-token $SUPABASE_ACCESS_TOKEN
      
      - name: Link to Supabase project
        working-directory: ./backend/supabase
        run: supabase link --project-ref $SUPABASE_PROJECT_ID
      
      - name: Deploy database migrations
        working-directory: ./backend/supabase
        run: supabase db push
      
      - name: Deploy Edge Functions
        working-directory: ./backend/supabase
        run: supabase functions deploy --project-ref $SUPABASE_PROJECT_ID

      - name: Verify deployment
        working-directory: ./backend/supabase
        run: |
          echo "✅ Supabase deployment completed"
          echo "Database migrations applied"
          echo "Edge functions deployed"
